
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED,ACCOUNT_NON_LOCKED, CONFIRMED, LOGIN_ATTEMPTS) VALUES (1, 'gema123', '$2a$12$g4vJN.NUij6Nm6msU4By7Oa7rNVB12wUg91XLrGW6eeG4Sij5sWhq', 'Sasa', 'Gemovic', 'admin@admin.com', 1,1, 1,0);


-- Uloge 
INSERT INTO ROLE (ID, NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO ROLE (ID, NAME) VALUES (2, 'ROLE_REGULAR');
INSERT INTO ROLE (ID, NAME) VALUES (3, 'ROLE_AGENT');
-- Uloge korisnika
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 2);
--INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 3);

-- Permisije
INSERT INTO PERMISSION (ID, NAME) VALUES (1, 'CREATE_CERTIFICATE');
INSERT INTO PERMISSION (ID, NAME) VALUES (2, 'READ_CERTIFICATE');
INSERT INTO PERMISSION (ID, NAME) VALUES (3, 'UPDATE_CERTIFICATE');
INSERT INTO PERMISSION (ID, NAME) VALUES (4, 'DELETE_CERTIFICATE');
INSERT INTO PERMISSION (ID, NAME) VALUES (5, 'NEKA_PERMISIJA');
-- Permisije admina
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 1);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 2);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 3);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 4);
-- Permisije korisnika
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (2, 2);
