
package com.bookingAgent.agentBackend.ws;


import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccomodationService", targetNamespace = "http://server.project2018.example.com/soap", wsdlLocation = "http://localhost:8080/ws/test.wsdl")
public class AccomodationService
    extends Service
{

    private final static URL ACCOMODATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCOMODATIONSERVICE_EXCEPTION;
    private final static QName ACCOMODATIONSERVICE_QNAME = new QName("http://server.project2018.example.com/soap", "AccomodationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://localhost:8443/ws/test.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOMODATIONSERVICE_WSDL_LOCATION = url;
        ACCOMODATIONSERVICE_EXCEPTION = e;
    }

    public AccomodationService() {
        super(__getWsdlLocation(), ACCOMODATIONSERVICE_QNAME);
    }

    public AccomodationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOMODATIONSERVICE_QNAME, features);
    }

    public AccomodationService(URL wsdlLocation) {
        super(wsdlLocation, ACCOMODATIONSERVICE_QNAME);
    }

    public AccomodationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOMODATIONSERVICE_QNAME, features);
    }

    public AccomodationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccomodationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccomodationPort
     */
    @WebEndpoint(name = "AccomodationPortSoap11")
    public AccomodationPort getAccomodationPortSoap11() {
        return super.getPort(new QName("http://server.project2018.example.com/soap", "AccomodationPortSoap11"), AccomodationPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccomodationPort
     */
    @WebEndpoint(name = "AccomodationPortSoap11")
    public AccomodationPort getAccomodationPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.project2018.example.com/soap", "AccomodationPortSoap11"), AccomodationPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOMODATIONSERVICE_EXCEPTION!= null) {
            throw ACCOMODATIONSERVICE_EXCEPTION;
        }
        return ACCOMODATIONSERVICE_WSDL_LOCATION;
    }

}
