
package com.bookingAgent.agentBackend.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccomodationPort", targetNamespace = "http://server.project2018.example.com/soap")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccomodationPort {


    /**
     * 
     * @param getAccommodationRequest
     * @return
     *     returns com.example.project2018.server.soap.GetAccommodationResponse
     */
    @WebMethod
    @WebResult(name = "getAccommodationResponse", targetNamespace = "http://server.project2018.example.com/soap", partName = "getAccommodationResponse")
    public GetAccommodationResponse getAccommodation(
        @WebParam(name = "getAccommodationRequest", targetNamespace = "http://server.project2018.example.com/soap", partName = "getAccommodationRequest")
        GetAccommodationRequest getAccommodationRequest);

}
